NUM_SMALL_CASES = 10
NUM_MEDIUM_CASES = 48

SMALL_K_SCHEDULE = [4, 6, 8, 10]
N_SMALL_K = len(SMALL_K_SCHEDULE)

SMALL_SAMPLE_SIZE = 1e2
MEDIUM_SAMPLE_SIZE = 1e3
LARGE_SAMPLE_SIZE = 1e4

MEDIUM_SIZE_SCHEDULE = [1e3, 2e3, 3e3, 4e3, 5e3]
NUM_MEDIUM_SIZES = len(MEDIUM_SIZE_SCHEDULE)

MNIST_SIZE_MULTIPLIERS = [2, 4, 7]
SCRNA_SIZE_MULTIPLIERS = [2, 3, 4]

PROPORTION_PASSING = 0.8
SCALING_EXPONENT = 1.2
