# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a new KMedoids object.
#'
#' @return an external ptr (Rcpp::XPtr) to a KMedoids object instance.
.KMedoids__new <- function(k, max_iter, build_confidence, swap_confidence) {
    .Call('_BanditPAM_KMedoids__new', PACKAGE = 'BanditPAM', k, max_iter, build_confidence, swap_confidence)
}

#' Fit the KMedoids algorthm given the data and loss
#'
#' @param xp the km::KMedoids Object XPtr
#' @param data the data matrix
#' @param loss the loss indicator
#' @param distMat the optional distance matrix
.KMedoids__fit <- function(xp, data, loss, distMat = NULL) {
    invisible(.Call('_BanditPAM_KMedoids__fit', PACKAGE = 'BanditPAM', xp, data, loss, distMat))
}

#' Return the final medoids
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__get_medoids_final <- function(xp) {
    .Call('_BanditPAM_KMedoids__get_medoids_final', PACKAGE = 'BanditPAM', xp)
}

#' Return the number of medoids property k
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__get_k <- function(xp) {
    .Call('_BanditPAM_KMedoids__get_k', PACKAGE = 'BanditPAM', xp)
}

#' Set the number of medoids property k
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__set_k <- function(xp, k) {
    invisible(.Call('_BanditPAM_KMedoids__set_k', PACKAGE = 'BanditPAM', xp, k))
}

#' Return the max_iter property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__get_max_iter <- function(xp) {
    .Call('_BanditPAM_KMedoids__get_max_iter', PACKAGE = 'BanditPAM', xp)
}

#' Set the max_iter property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__set_iter <- function(xp, m) {
    invisible(.Call('_BanditPAM_KMedoids__set_max_iter', PACKAGE = 'BanditPAM', xp, m))
}

#' Return the build_conf property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__get_build_conf <- function(xp) {
    .Call('_BanditPAM_KMedoids__get_build_conf', PACKAGE = 'BanditPAM', xp)
}

#' Set the build_conf property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__set_iter <- function(xp, bc) {
    invisible(.Call('_BanditPAM_KMedoids__set_build_conf', PACKAGE = 'BanditPAM', xp, bc))
}

#' Return the swap_conf property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__get_swap_conf <- function(xp) {
    .Call('_BanditPAM_KMedoids__get_swap_conf', PACKAGE = 'BanditPAM', xp)
}

#' Set the swap_conf property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__set_iter <- function(xp, bc) {
    invisible(.Call('_BanditPAM_KMedoids__set_swap_conf', PACKAGE = 'BanditPAM', xp, bc))
}

#' Return the loss_fn property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__get_loss_fn <- function(xp) {
    .Call('_BanditPAM_KMedoids__get_loss_fn', PACKAGE = 'BanditPAM', xp)
}

#' Set the loss_fn property
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__set_loss_fn <- function(xp, loss_fn) {
    invisible(.Call('_BanditPAM_KMedoids__set_loss_fn', PACKAGE = 'BanditPAM', xp, loss_fn))
}

