# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return the number of threads banditpam is using
#' @return the number of threads banditpam is using
bpam_num_threads <- function() {
    .Call('_banditpam_bpam_num_threads', PACKAGE = 'banditpam')
}

.KMedoids__new <- function(k, alg, max_iter, build_confidence, swap_confidence) {
    .Call('_banditpam_KMedoids__new', PACKAGE = 'banditpam', k, alg, max_iter, build_confidence, swap_confidence)
}

.KMedoids__fit <- function(xp, data, loss, distMat = NULL) {
    invisible(.Call('_banditpam_KMedoids__fit', PACKAGE = 'banditpam', xp, data, loss, distMat))
}

.KMedoids__get_medoids_final <- function(xp) {
    .Call('_banditpam_KMedoids__get_medoids_final', PACKAGE = 'banditpam', xp)
}

.KMedoids__get_k <- function(xp) {
    .Call('_banditpam_KMedoids__get_k', PACKAGE = 'banditpam', xp)
}

.KMedoids__set_k <- function(xp, k) {
    invisible(.Call('_banditpam_KMedoids__set_k', PACKAGE = 'banditpam', xp, k))
}

.KMedoids__get_max_iter <- function(xp) {
    .Call('_banditpam_KMedoids__get_max_iter', PACKAGE = 'banditpam', xp)
}

.KMedoids__set_iter <- function(xp, m) {
    invisible(.Call('_banditpam_KMedoids__set_max_iter', PACKAGE = 'banditpam', xp, m))
}

.KMedoids__get_build_conf <- function(xp) {
    .Call('_banditpam_KMedoids__get_build_conf', PACKAGE = 'banditpam', xp)
}

.KMedoids__set_iter <- function(xp, bc) {
    invisible(.Call('_banditpam_KMedoids__set_build_conf', PACKAGE = 'banditpam', xp, bc))
}

.KMedoids__get_swap_conf <- function(xp) {
    .Call('_banditpam_KMedoids__get_swap_conf', PACKAGE = 'banditpam', xp)
}

.KMedoids__set_iter <- function(xp, bc) {
    invisible(.Call('_banditpam_KMedoids__set_swap_conf', PACKAGE = 'banditpam', xp, bc))
}

.KMedoids__get_loss_fn <- function(xp) {
    .Call('_banditpam_KMedoids__get_loss_fn', PACKAGE = 'banditpam', xp)
}

.KMedoids__set_loss_fn <- function(xp, loss_fn) {
    invisible(.Call('_banditpam_KMedoids__set_loss_fn', PACKAGE = 'banditpam', xp, loss_fn))
}

.KMedoids__get_statistic <- function(xp, what) {
    .Call('_banditpam_KMedoids__get_statistic', PACKAGE = 'banditpam', xp, what)
}

